name: LineageOS building
on:
  push:
    branches:
      - cm-14.1
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: docker:jakesoso/cm_build:los14.1

    - name: Build and Deploy
      uses: docker:jakesoso/cm_build:los14.1:los14.1 /bin/bash -c "bash build.sh"
